version: '2'

services:
  ghost:
    image: ghost
    volumes:
      - ./_content:/var/lib/ghost
    restart: "on-failure:3"
  caddy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    links:
      - ghost
    restart: "on-failure:3"
  dropbox:
    image: janeczku/dropbox
    restart: "on-failure:3"
    volumes:
      - ./_backup:/dbox/Dropbox
  backup:
    image: bennetimo/ghost-backup
    volumes_from:
      - ghost
    volumes:
      - ./_backup:/dbox/Dropbox
    environment:
      BACKUP_LOCATION: "/dbox/Dropbox/"
      BACKUPS_RETAIN_LIMIT: 1
    restart: "on-failure:3"
