version: '2'

services:
  ghost:
    image: ghost
    volumes:
      - ./_content:/var/lib/ghost
  caddy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    links:
      - ghost
